### ISSUE TITLE
What does the T_{prep}^{c}(x) in formulation of T^{m}(x) mean?

### ISSUE THREAD

**Issue by Zongshun96** [cake-lab/PieSlicer#1]
Greetings,
Interesting paper and congratulations!

I have a question regarding your paper formulation. What does the $T_{prep}^{c}(x)$ in formulation of $T^{m}(x)$ mean? I thought you would completely offload the preprocessing to either device or cloud, so why do we have the extra $T_{prep}^{c}(x)$ in $T^{m}(x)$?

Thanks,
Zongshun

**Comment by samogden** [comment]
Hi Zongshun!  Sorry for the slow response!
Good question, and one that we could've better addressed in the paper.  Even when doing inference on-device there's a small time required to convert the resized data to a tensor and prepare it for inference.  While it's more or less negligible (you can see in Figure 3d that it's fairly consistent and generally a few orders of magnitude less than the other components) we thought it was best to still include it in our formulation.  At the end of Section 4.2 we discuss it and why we chose to use a uniform assumption of 1ms for it.

Thanks!
Sam
